@endpoint = http://localhost:{{$dotenv PORT}}/api
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

### Connexion ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "axel@axel.com",
    "password": "secret"
}

###

### Connexion NON ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "michael@example.com",
    "password": "secret"
}

### REFRESH TOKEN FIRST TIME
# @name login
POST {{endpoint}}/auth/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
### Récupérer tous les article public pour la homepage
GET {{ endpoint }}/articles?home=true

### Récupérer tous les article public
GET {{ endpoint }}/articles

### Récupérer tous les article privé ADMIN
GET {{ endpoint }}/articles/admin
Authorization: Bearer {{accessToken}}

### Récupérer un article privé ADMIN
GET {{ endpoint }}/articles/admin/article-title-testssssssszzz
Authorization: Bearer {{accessToken}}

### Récupérer un article
GET {{ endpoint }}/articles/article-title-test

### CREATION ARTICLE
POST {{ endpoint }}/articles/
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Bearer {{accessToken}}

--boundary_value
Content-Disposition: form-data; name="img"; filename="test.webp"
Content-Type: image/webp

@./test.pdf
--boundary_value
Content-Disposition: form-data; name="title"

article title testsss
--boundary_value
Content-Disposition: form-data; name="content"

roberts
--boundary_value
Content-Disposition: form-data; name="publication_date"

2024-06-21T08:00:00.581Z
--boundary_value
Content-Disposition: form-data; name="figcaption"

hhpassasa
--boundary_value--


### MODIFICATION D'UN ARTICLE
PATCH {{ endpoint }}/articles/12
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Bearer {{accessToken}}

--boundary_value
Content-Disposition: form-data; name="img"; filename="test.webp"
Content-Type: image/webp

@./test.pdf
--boundary_value
Content-Disposition: form-data; name="title"

1 article title testsss
--boundary_value
Content-Disposition: form-data; name="content"

roberts
--boundary_value
Content-Disposition: form-data; name="publication_date"

2023-06-21T08:00:00.581Z
--boundary_value
Content-Disposition: form-data; name="figcaption"

hhpassasa
--boundary_value--


### SUPPRESSION D'UN ARTICLE
DELETE {{endpoint}}/articles/article-title-testsss
Authorization: Bearer {{accessToken}}

### CREATION D'un lien entre un article et une category
POST {{ endpoint }}/articles/nouvel-article/category/1
Authorization: Bearer {{accessToken}}


### SUPPRESSION D'un lien entre un article et une category
DELETE {{endpoint}}/articles/nouvel-article/category/1
Authorization: Bearer {{accessToken}}


