@endpoint = http://localhost:{{$dotenv PORT}}/api
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

### Connexion ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "axel@axel.com",
    "password": "secret"
}


### REFRESH TOKEN FIRST TIME
# @name login
POST {{endpoint}}/auth/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
### Récupérer tous les évents/calendrier/match
GET {{ endpoint }}/calendar

### Récupérer 1 match à venir et 1 passé pour la homepage
GET {{ endpoint }}/calendar?home=true

### Création d'un évent

POST {{ endpoint }}/calendar
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Bearer {{accessToken}}


--boundary_value
Content-Disposition: form-data; name="img"; filename="test.webp"
Content-Type: image/webp

@./test.pdf
--boundary_value
Content-Disposition: form-data; name="event_name"

tournoi-world
--boundary_value
Content-Disposition: form-data; name="event_date"

2023-06-10 18:00:00
--boundary_value
Content-Disposition: form-data; name="adversary_name"

Team D
--boundary_value
Content-Disposition: form-data; name="adversary_name_short"

TD
--boundary_value--

### Récupérer un évent

GET  {{ endpoint }}/calendar/6


### Modification d'un évent
PATCH {{ endpoint }}/calendar/5
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Bearer {{accessToken}}


--boundary_value
Content-Disposition: form-data; name="img"; filename="test.webp"
Content-Type: image/webp

@./test.pdf
--boundary_value
Content-Disposition: form-data; name="event_name"

tournoi-world
--boundary_value
Content-Disposition: form-data; name="event_date"

2023-06-10 18:00:00
--boundary_value
Content-Disposition: form-data; name="adversary_name"

Team D
--boundary_value
Content-Disposition: form-data; name="adversary_name_short"

TD
--boundary_value--

### Suppression d'un évent

DELETE {{ endpoint }}/calendar/5
Authorization: Bearer {{accessToken}}

