@endpoint = http://localhost:{{$dotenv PORT}}/api
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

### Connexion ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "axel@axel.com",
    "password": "passwordaxel"
}

###

### REFRESH TOKEN FIRST TIME
# @name login
POST {{endpoint}}/auth/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}


### RECUPÉRATION DES CATÉGORIE
GET {{ endpoint }}/category/
content-type: application/json


### CREATION D'UNE CATÉGORIE
POST {{ endpoint }}/category/
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "label": "cod"
}


### MODIFICATION D'UNE CATÉGORIE
PATCH {{ endpoint }}/category/5
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "label": "Call of Duty"
}


### SUPPRESSION D'UNE CATÉGORIE
DELETE {{endpoint}}/category/5
Authorization: Bearer {{accessToken}}


