@endpoint = http://localhost:{{$dotenv PORT}}/api
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

### Connexion ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "axel@axel.com",
    "password": "secret"
}

###

### Connexion NON ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "michael@example.com",
    "password": "secret"
}

### REFRESH TOKEN FIRST TIME
# @name login
POST {{endpoint}}/auth/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
