@endpoint = http://localhost:{{$dotenv PORT}}/api
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

### Connexion ADMIN
# @name login
POST {{endpoint}}/auth/login
content-type: application/json

{
    "email": "axel@axel.com",
    "password": "secret"
}

### REFRESH TOKEN FIRST TIME
# @name login
POST {{endpoint}}/auth/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}



### Récupérer tous les membres
GET {{ endpoint }}/team


### Récupérer tous les membres pour la home page
GET {{ endpoint }}/team?home=true

### Création d'un joueur
POST {{ endpoint }}/team/
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Bearer {{accessToken}}

--boundary_value
Content-Disposition: form-data; name="img"; filename="test.webp"
Content-Type: image/webp

@./test.pdf
--boundary_value
Content-Disposition: form-data; name="user_name"

noobDu34
--boundary_value
Content-Disposition: form-data; name="first_name"

Kevin
--boundary_value
Content-Disposition: form-data; name="last_name"

roberts
--boundary_value
Content-Disposition: form-data; name="description"

sasasas
--boundary_value
Content-Disposition: form-data; name="role"

hhpassasa
--boundary_value--

### Récupérer un joueur

GET {{ endpoint }}/team/noobDu34


### Modification d'un joueur

PATCH  {{endpoint}}/team/6
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Bearer {{accessToken}}

--boundary_value
Content-Disposition: form-data; name="img"; filename="test.webp"
Content-Type: image/webp

@./test.pdf
--boundary_value
Content-Disposition: form-data; name="user_name"

article-title-testsssss
--boundary_value
Content-Disposition: form-data; name="first_name"

article title testsss
--boundary_value
Content-Disposition: form-data; name="last_name"

roberts
--boundary_value
Content-Disposition: form-data; name="description"

sasasas
--boundary_value
Content-Disposition: form-data; name="role"

hhpassasa
--boundary_value--

### Suppression d'un joueur

DELETE {{ endpoint }}/team/noobDu34
Authorization: Bearer {{accessToken}}


### CREATION D'un lien entre un joueur et un media

POST {{ endpoint }}/team/joueur2/media/2
Authorization: Bearer {{accessToken}}

### CREATION D'un lien entre un joueur et un media

POST {{ endpoint }}/team/joueur2/setup/2
Authorization: Bearer {{accessToken}}

### SUPPRESSION D'un lien entre un joueur et un media

DELETE {{ endpoint }}/team/joueur2/media/2
Authorization: Bearer {{accessToken}}

### SUPPRESSION D'un lien entre un joueur et un setup
DELETE {{ endpoint }}/team/joueur2/setup/2
Authorization: Bearer {{accessToken}}
